version: '3'
services:
  app:
    build: .  # Tells docker compose where the Dockerfile is
    ports:
      - "8080:8080"
    volumes:
      - .:/app  
    environment:
      - PORT=8080  
    command: ["npx", "nodemon", "src/index.js"]  # Command for development
    profiles:
      - development
    
    app-prod:

      build: .
      ports:
        - "8080:8080"
      volumes:
        - .:/app
      command: ["npm", "start"]  # Command for production
      profiles:
        - production
