version: '3'
services:
  app:
    build:
      context: .  # The current directory is used as the build context # Optional if the Dockerfile is named Dockerfile
    ports:
      - "8080:8080"  # Maps container's port 8080 to the host's port 8080
    volumes:
      - .:/app  
    environment:
      - PORT=8080  
