
services:
  app:
    build: .  
    ports:
      - "8080:8080"
    volumes:
      - .:/app  
      - /app/node_modules  # Isolate node_modules from rest of system
    environment:
      - PORT=8080  
    command: ["npx", "tsx", "src/index.ts" ]  # Command for development
    profiles:
      - development
    
  app-prod:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules  # Isolate node_modules from rest of system
    command: ["npm", "start"]  # Command for production
    profiles:
      - production
